---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: activityservice
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"    
  name: activityservice
spec:
  clusterIP: None
  ports:
  - name: http-lagom-api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: activityservice
