---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chirpservice
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"    
  name: chirpservice-akka-remoting
spec:
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    app: chirpservice
