---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"    
  name: web
spec:
  ports:
  - name: http-play
    port: 9000
  selector:
    app: web
