---
apiVersion: v1
kind: Service
metadata:
  name: nginx-default-backend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx-default-backend
