chirper:
  ingress:
    host: chirper-new.us-south.containers.mybluemix.net
    tls:
      secret: chirper-new
  imagePullPolicy: Always
  cassandra:
    service: _cql._tcp.chirper-cassandra.default.svc.cluster.local

  activity_stream:
    replicas: 2
    secret: SECRET
    image:
      repo: registry.ng.bluemix.net/chirper/activity-stream-impl
      tag: 1.0-SNAPSHOT

  chirp:
    replicas: 2
    secret: SECRET
    image:
      repo: registry.ng.bluemix.net/chirper/chirp-impl
      tag: 1.0-SNAPSHOT

  friend:
    replicas: 2
    secret: SECRET
    image:
      repo: registry.ng.bluemix.net/chirper/friend-impl
      tag: 1.0-SNAPSHOT

  front_end:
    replicas: 2
    image:
      repo: registry.ng.bluemix.net/chirper/front-end
      tag: 1.0-SNAPSHOT

  nginx:
    backend:
      replicas: 2
      image:
        repo: gcr.io/google_containers/defaultbackend
        tag: "1.0"

    ingress:
      replicas: 2
      type: ClusterIP
      image:
        repo: gcr.io/google_containers/nginx-ingress-controller
        tag: "0.9.0-beta.10"

cassandra:
  image:
    repo: gcr.io/google-samples/cassandra
    tag: v12
  persistence:
    enabled: true
    storageClass: ibmc-file-bronze
