language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - mvn test -B
cache:
  directories:
    - $HOME/.m2
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.m2/repository/com/lightbend/lagom/sample/chirper
notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/773aba95141768c32dae
    on_success: always
    on_failure: always
