language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - mvn test -B
notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/773aba95141768c32dae
    on_success: always
    on_failure: always
