chirper:
  cassandra:
    service: _cql._tcp.chirper-cassandra.default.svc.cluster.local
  ingress:
    host: chirper-new.us-south.containers.mybluemix.net
    tls:
      secret: chirper-new

  activity_stream:
    replicas: 2
    secret: SECRET
    image:
      repo: ibmcode/chirper_activity-stream-impl
      tag: 1.0-SNAPSHOT

  chirp:
    replicas: 2
    secret: SECRET
    image:
      repo: ibmcode/chirper_chirp-impl
      tag: 1.0-SNAPSHOT

  friend:
    replicas: 2
    secret: SECRET
    image:
      repo: ibmcode/chirper_friend-impl
      tag: 1.0-SNAPSHOT

  front_end:
    replicas: 2
    image:
      repo: ibmcode/chirper_front-end
      tag: 1.0-SNAPSHOT

  nginx:
    backend:
      replicas: 2
      image:
        repo: gcr.io/google_containers/defaultbackend
        tag: "1.0"

    ingress:
      replicas: 2
      type: ClusterIP
      image:
        repo: gcr.io/google_containers/nginx-ingress-controller
        tag: "0.9.0-beta.10"

cassandra:
  image:
    repo: gcr.io/google-samples/cassandra
    tag: v12
  persistence:
    enabled: true
